#pragma once

#define MAX_ENTITIES 100
#define PIXELS_PER_METER 50.0f
#define MAX_DRAG_METERS 2.5f
#define LAUNCH_STRENGTH 6.0f

#define TOTAL_BIRDS 3
#define BIRD_RADIUS 0.35f
#define BIRD_DENSITY 4.0f
#define HIT_SPEED_THRESHOLD 3.0f
#define SETTLE_SPEED_THRESHOLD 0.5f